### ISSUE TITLE
[ERROR] Digital envelope routines::unsupported

### ISSUE THREAD

**Issue by emidev98** [bitcoinjs/bip32#59] opened 2022-04-05 08:38 UTC
Hello, we have found that the library has breaking changes with node v17. 
The reason why is [explained in this webiste](https://itsmycode.com/error-digital-envelope-routines-unsupported/), but a tinny extract from the website says: 
> This error is because node.js 17 uses OpenSSL3, which has changed code for initialization context of md family (including md4), and this is a breaking change.

NPM/NodeJs:
![image](https://user-images.githubusercontent.com/49301655/161713441-2294a4e1-71b2-495c-bc16-4b026b812275.png)

Error:
![image](https://user-images.githubusercontent.com/49301655/161713579-977d26e4-b223-46a5-9e6e-2dd7969b4494.png)

Please let us know if more information is needed or if we can help on a different way

**Comment by junderw** [comment] 2022-04-05 10:13
It seems like the only way to "fix" this is to remove node based hashing and only use pure JS hashing.

Alternatively, we could also use WASM.

**Comment by junderw** [comment] 2022-04-05 10:15
or actually this might be better fixed upstream: https://github.com/crypto-browserify/createHash

**Comment by junderw** [comment] 2022-04-05 10:19
......? I looked at Node v17 API for createHash... it hasn't really changed...

Is it just that OpenSSL no longer supports ripemd160?

**Comment by emidev98** [comment] 2022-04-05 10:22
I could find this https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md#openssl-30

**Comment by motorina0** [comment] 2022-04-05 13:41
> @motorina0 this sounds like fun...

yes, but you are too fast. Do you ever sleep?

Just to summarize:
- this is indeed caused by Node `v17` upgrading to `OpenSSL 3.0` (from `OpenSSL 1.1.1`). Reported also on [other projects](https://github.com/webpack/webpack/issues/14532).
- quick fixes:
  - either use the `--openssl-legacy-provider` flag (`NODE_OPTIONS=--openssl-legacy-provider npm run test`)
  - or, use directly the browser version (`crypto.ts`):
     - `const createHash = require('create-hash/browser');`
- long term fix suggested here: https://github.com/crypto-browserify/createHash/issues/29

**Comment by junderw** [comment] 2022-09-25 12:06
Fixed in 3.1.0

**Closed by junderw** 2022-09-25 12:06 UTC
